---
ID: "a8bc93f0-a32c-4254-9731-8724576fafb6"
Parent: "b6ef3982-5312-46ca-8934-e3dad6f0d53a"
Template: "b6ef3982-5312-46ca-8934-e3dad6f0d53a"
Path: /sitecore/templates/Feature/Usergroup/UserGroup/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T023345Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
