---
ID: "a8bc93f0-a32c-4254-9731-8724576fafb6"
Parent: "b6ef3982-5312-46ca-8934-e3dad6f0d53a"
Template: "b6ef3982-5312-46ca-8934-e3dad6f0d53a"
Path: /sitecore/templates/Feature/Usergroup/UserGroup/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{D390C691-8911-4EC1-AD8F-41EAC0A8D1E5}">
        <r
          id="{6775AD41-0304-471C-B529-B5A08DA65538}"
          ph="body"
          uid="{3C079B34-5658-4842-89A3-D97D105CB8B3}" />
        <r
          id="{563FF068-0DB3-45DD-BDC9-20516323F25E}"
          ph="body"
          uid="{E967B3B7-38ED-415E-BEE7-5B1C9FF0FDF6}" />
        <r
          ds="{747EB956-C4AD-4169-8305-90AF3E21C523}"
          id="{6B5B0FE6-5C85-4487-BA7E-F8C2ECC186A8}"
          par=""
          ph="createforms"
          uid="{D5950C1C-F746-4A55-8BCC-AAE87A61B53A}">
          <rls>
            <ruleset
              pet="true">
              <rule
                name="organizer only"
                uid="{54379626-67EE-459C-8EC5-E91470D53080}">
                <conditions>
                  <condition
                    id="{61149788-6E2A-4F8F-BB29-5E8D595B6957}"
                    uid="2DFCAF9922A54A169604F7C419E2AAF6"
                    FieldName="Organizers" />
                </conditions>
              </rule>
              <rule
                uid="{00000000-0000-0000-0000-000000000000}"
                name="Default">
                <conditions>
                  <condition
                    id="{4888ABBB-F17D-4485-B14B-842413F88732}"
                    uid="70EDCBF382C0452D8635C520D5EE142A" />
                </conditions>
                <actions>
                  <action
                    id="{25F351A1-712D-45F8-857D-8AD95BB2ACE9}"
                    uid="9CB9BD2239E34CDAB654B2514A09BCFC" />
                </actions>
              </rule>
            </ruleset>
          </rls>
        </r>
        <r
          ds="{AD1650F7-0CE9-43C3-98CC-9C330F017AA4}"
          id="{6B5B0FE6-5C85-4487-BA7E-F8C2ECC186A8}"
          par=""
          ph="body"
          uid="{FFF92114-3520-4AEA-ACAD-450B987195FF}">
          <rls>
            <ruleset
              pet="true">
              <rule
                name="Where the user is anonymous"
                uid="{0F62357B-8833-4828-90B8-3BC0C7A634C6}">
                <conditions>
                  <condition
                    id="{EA0642FA-500B-4B2F-B264-765E771C516F}"
                    uid="CA61BA72E29B4D908A167224614BA563" />
                </conditions>
                <actions>
                  <action
                    id="{25F351A1-712D-45F8-857D-8AD95BB2ACE9}"
                    uid="F2A3D5865C7148609B1295BF8087C984" />
                </actions>
              </rule>
              <rule
                name="Where the user is already on list"
                uid="{0A668FB3-96EB-4A63-A154-38DA9B44124A}">
                <conditions>
                  <condition
                    id="{61149788-6E2A-4F8F-BB29-5E8D595B6957}"
                    uid="BCDA89D4D4A2438F99A508BEC586C5CE"
                    FieldName="Members" />
                </conditions>
                <actions>
                  <action
                    id="{0F3C6BEC-E56B-4875-93D7-2846A75881D2}"
                    uid="6AF6F21D90BD47F885DFBB35F912A3B1"
                    DataSource="{60026F75-7B64-4CD6-B06B-802EE4B4C362}" />
                </actions>
              </rule>
              <rule
                uid="{00000000-0000-0000-0000-000000000000}"
                name="Default">
                <conditions>
                  <condition
                    id="{4888ABBB-F17D-4485-B14B-842413F88732}"
                    uid="DB9B68DE4106494F8DB86DA74C25C7D2" />
                </conditions>
                <actions>
                  <action
                    id="{0F3C6BEC-E56B-4875-93D7-2846A75881D2}"
                    uid="A7E78309F34846E583C7A79AFDA6030C"
                    DataSource="{AD1650F7-0CE9-43C3-98CC-9C330F017AA4}" />
                </actions>
              </rule>
            </ruleset>
          </rls>
        </r>
        <r
          ds="{A319F882-E9E8-408E-BAB2-9B7C1A4302C2}"
          id="{6B5B0FE6-5C85-4487-BA7E-F8C2ECC186A8}"
          par=""
          ph="nav-auth"
          uid="{9E5F3D56-3414-4AC1-9D03-CC87A6E86369}" />
        <r
          ds="{51C01E26-DB53-4CFE-BD8C-C3512267B215}"
          id="{6B5B0FE6-5C85-4487-BA7E-F8C2ECC186A8}"
          par=""
          ph="nav-not-auth"
          uid="{D39AAFD0-DA3F-44F1-9283-036D58D1CAEE}" />
        <r
          id="{1EBF60B5-5DF7-4A3E-9CED-46A3B5284940}"
          ph="header"
          uid="{474FBACE-2F08-4EAC-92B0-D27FE9F9BA20}" />
        <r
          id="{5C23CD03-4D9E-4E0A-A1B2-B3B3571F986D}"
          ph="nav"
          uid="{D79CFB28-0E3B-4FBE-9785-31FA1B3E7B06}" />
        <r
          id="{46FD973B-97D4-4BEE-B76F-EEFFEAA818E1}"
          ph="body"
          uid="{3FF06C07-C06F-4BC5-9F90-FC6AF6A070F0}" />
        <r
          id="{B1E6B902-E085-45FA-BF1B-CD2B48034E8C}"
          ph="body"
          uid="{2EB865D5-00D8-46C5-88ED-CC92C68ED4D9}" />
        <r
          id="{510C62CA-916F-4DB4-B67C-C283CFF37FEC}"
          ph="body"
          uid="{EA89A5AE-DA1D-4544-8ADA-DD2A4D3C5683}">
          <rls>
            <ruleset
              pet="true">
              <rule
                name="Organizer only"
                uid="{6B56144E-A872-499A-9B01-8EC8E34F88C6}">
                <conditions>
                  <condition
                    id="{61149788-6E2A-4F8F-BB29-5E8D595B6957}"
                    uid="6025C0C340AE4283B53FEB6E0F93D3DC"
                    FieldName="Organizers" />
                </conditions>
              </rule>
              <rule
                uid="{00000000-0000-0000-0000-000000000000}"
                name="Default">
                <conditions>
                  <condition
                    id="{4888ABBB-F17D-4485-B14B-842413F88732}"
                    uid="D33E2E7D358843AF9E3789E24100E497" />
                </conditions>
                <actions>
                  <action
                    id="{25F351A1-712D-45F8-857D-8AD95BB2ACE9}"
                    uid="D70D88A46C414257BE6935459C10B74A" />
                </actions>
              </rule>
            </ruleset>
          </rls>
        </r>
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T023345Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
